### ISSUE TITLE
C++ compilation error with g++15 caused by including `<cstdint>` but using `int64_t` instead of `std::int64_t`

### ISSUE THREAD

**Issue by DominiquePelle-TomTom** [ndsev/zserio#691]
**Zserio version and language**
Zserio: 2.16.0
Language: C++

**Describe the bug**

Generated C++ code includes `<cstdint>` but uses types like `uint64_t`, `int64_t` (etc.) without the `std::` namespace prefix. This is incorrect and not portable. It causes compilation errors when building with gcc15 such as:
```
/home/dope/.conan/data/zserio/2.16.0/_/_/build/2a1643475ff774383687d1e8922f3bc3015406f5/src/compiler/extensions/cpp/runtime/src/zserio/JsonEncoder.h: In static member function ‘static void zserio::JsonEncoder::encodeIntegral(std::ostream&, T)’:
/home/dope/.conan/data/zserio/2.16.0/_/_/build/2a1643475ff774383687d1e8922f3bc3015406f5/src/compiler/extensions/cpp/runtime/src/zserio/JsonEncoder.h:67:76: error: ‘uint64_t’ was not declared in this scope [-Wtemplate-body]
   67 |     using U = typename std::conditional<std::is_signed<T>::value, int64_t, uint64_t>::type;
      |                                                                            ^~~~~~~~
``` 

To fix it, either:
*  use `#include <cstdint>` and `std::uint64_t` in zserio code (preferred and more modern solution, but you have to replace many `int64_t` into `std::int64_t`, same for other types like `int8_t`, etc.)
* or use `#include <stdint.h>` and `int64_t` in zserio code.  This is the less preferred and is the old pre-c++11 way. Since it does not use namespace, it is more prone to name collisions.

**How to reproduce**
N/A

**Expected behavior**
Generated C++ code should compile on any compiler

**Comment by mikir** [comment]
Thanks for the report. Currently, we directly support only g++7 and g++11. We should investigate this to understand clearly the differencies between gcc versions.

I will put this issue to the current milestone. However, we are working on C++17 generator now, so it will take some time. If this issue is urgent, please write us a note here. Thanks.

**Comment by tope99** [comment]
I can't reproduce the compilation error with gcc-15.1 or any other compiler (tested on godbolt.org). Do you use some extra settings? Modules?

**Comment by DominiquePelle-TomTom** [comment]
> I can't reproduce the compilation error with gcc-15.1 or any other compiler (tested on godbolt.org). Do you use some extra settings? Modules?

I'm not sure why.  Maybe we're using a different libstdc++ or libc++ with gc-15.1.

Anyway, I can reproduce the same kind of error with a very simple piece of code. Try this which fails to compile with gcc-15.1 or with clang-20 for example, for the same reasons:

```
$ cat int.cpp
#include <stdint.h>

int foo() {
  const  std::int32_t i = 0;
  return i;
}
```


Build error with clang-15.1:
```
$ g++-15.1.0 -c int.cpp
int.cpp: In function ‘int foo()’:
int.cpp:4:15: error: ‘int32_t’ in namespace ‘std’ does not name a type
    4 |   const  std::int32_t i = 0;
      |               ^~~~~~~
int.cpp:5:10: error: ‘i’ was not declared in this scope
    5 |   return i;
      |
```

Also build error with clang++-20:
```
```

**Comment by DominiquePelle-TomTom** [comment]
@tope99  wrote:

> I can see your sample code won't compile but this is not a problem for zserio since we generate code with #include <cstdint> not with <stdint.h>
...
> If you include <cstdint> you can use the types with and without std prefix in all major compilers including gcc 15.1.


That is incorrect.



zserio includes `<cstdint>` but uses `int32_t` instead of `std::int32_t`.

That is not portable. It may only compile by chance, if the old `<stdint.h>` include happens to be included indirectly  (e.g. from inside some STL file.


I asked ChatGPT, which agrees with me:

> In C++, why does int32_t compile without namespace when I include <cstdint> with some compilers and requires the namespace std::int32_t  with other compilers?

Answer from ChatGPT:

This behavior is due to implementation-defined differences in how the C++ standard library headers (specifically <cstdint>) expose their contents, and it's rooted in how C++ wraps the C standard headers and namespaces.
✅ Quick Summary

    int32_t is defined in the C header <stdint.h>.

    In C++, you should include <cstdint> instead.

    int32_t is part of the std namespace in <cstdint>.

    Some compilers also put int32_t into the global namespace (though this is non-standard behavior).

📘 The C++ Standard

According to the C++ standard:

    All symbols from the C standard library that are included via <c...> headers must appear inside the std namespace.

So, when you write:

#include <cstdint>

You are supposed to access int32_t like:

std::int32_t myInt;

🧪 Why It Works Without std:: on Some Compilers

Some standard library implementations (notably GCC/libstdc++ or older MSVC versions) also bring these types into the global namespace for compatibility with C or older code, even when using <cstdint>.

For example:

    GCC: Will often expose int32_t in both :: (global) and std:: namespaces.

    Clang: Depends on the standard library used (libc++, libstdc++).

    MSVC: Tends to follow the standard more strictly in modern versions.

This is not guaranteed behavior and is technically a violation of the standard. It’s permitted because the compiler authors choose to offer it for practical reasons (like easier migration from C to C++).

🔧 Best Practice

Always use:

#include <cstdint>
std::int32_t myInt = 42;

Or bring it into scope explicitly if you want:

#include <cstdint>
using std::int32_t;
int32_t myInt = 42;

🚨 Gotcha: Including <stdint.h> Instead of <cstdint>

If you include the C-style header:

#include <stdint.h>

Then int32_t is placed in the global namespace, even in C++. This is legal because <stdint.h> is a C header.

🧩 Summary Table
Header	Namespace	Standard?	Common?
<cstdint>	std::	✅ Yes	✅ Yes
<cstdint>	global ::	❌ No	⚠️ Sometimes (GCC)
<stdint.h>	global ::	✅ (for C compatibility)	✅ Yes
🔍 Final Tip

If you want your code to be portable across compilers, always assume int32_t is in std::.

**Comment by DominiquePelle-TomTom** [comment]
I got the error when building out entire project with gcc-15.1 and I copied pasted the compilation error in the  bug description.

I admit that if I tried to compile a sample, program locally, I also do not get this error and godbolt also does not give the error.
However, this is just luck, since including `<cstdint>` requires using the namespace std. It does not really matter whether we can reproduce or not, since we know it's not portable use int32_t without namespace.

> Does it really come from zserio generated code or is it fabricated?

In the bug  description, we can see that the error came from `src/compiler/extensions/cpp/runtime/src/zserio/JsonEncoder.h` and I can see this file and it indeed uses `int64_t` here:

https://github.com/ndsev/zserio/blob/30df082575f1bae2ecc8aa37d82ea0d620e5bfa0/compiler/extensions/cpp/runtime/src/zserio/JsonEncoder.h#L67

Both the source of zserio and the generated code should use the namespace std for int64_t if `<cstdint>` is included.

**Comment by DominiquePelle-TomTom** [comment]
The fail where the compilation error happens ii.e. JsonEncoder.h includes neither `<cstdint>` nor `<stdint.h>`.  So it relies on it being indirectly included.  This is fragile as different versions of libstdc++ include different headers indirectly.

This may in fact be the root cause of the issue, even if it should also also use std::int64_t with namespace ideally.

**Comment by fklebert** [comment]
@mikir , @tope99 why don't you just fix it?! The standard is clear on this. It is a simple search/replace all on the codebase. I do not understand why this is even worth discussing. Waste of time and money...

**Comment by mikir** [comment]
Because the root cause of this issue is wrong header inclusions, we will fix this by changing of `#include <cstdint>` and `#include <cstddef>` to `#include <stdint.h>` and `#include <stddef.h>` in the C++ runtime library.

However, better and preferred solution will be to use `#include <cstddef>` and `#include <cstddef>` and namespace prefix `::std::` everywhere. This solution will require more effort, so I have created a special issue #708 for that.
